name: cipher.sha
version: 0.0.1
description: A sample command-line application.
#author: kyorohiro <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'
dependencies:
  bignum: any
  crypto: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
